[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Arc-Black-Living-Coral
Comment=A flat theme with transparent elements, based on original ARC-Theme, with new colors. Pantone Black 6C as background and Pantone Living Coral as accent
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Arc-Black-Living-Coral
MetacityTheme=Arc-Black-Living-Coral
IconTheme=gnome
CursorTheme=DMZ-Black
ButtonLayout=menu:minimize,maximize,close
